### ISSUE TITLE
es6 promise dublicate identifier

### ISSUE THREAD

**Issue by stepancar** [basarat/ntypescript#11]
Hello @basarat !
I have question. In my project i use es6-promise library;
i installed d.ts for it.
in tsconfig added es6-promise 
and in my main.ts expression

``` javascript
    import {Promise} from "es6-promise";
```

is available.
But compiler say that 'Promise' contains in es6.lib,
we have conflict between 2 files es6.lib and es6-promise.d.ts.
do you have any idea how to resolve it? 
i use latest ntypescript atom-typescript and ts-loader for webpack 
Thank you!

**Comment by stepancar** [comment]
solved: removed target es-6 from tsconfig

**Comment by basarat** [comment]
:rose:
