### ISSUE TITLE
minor: README / packacke.json example

### ISSUE THREAD

**Issue by sebilasse** [basarat/ntypescript#14]
see README : "Install"
or in your package.json
`npm install ntypescript@latest --save --save-exact`

Shouldn't it mention the package.json `json member` here ?
The `npm install` could become an extra line.

Just think it might be misleading for newbies...

**Comment by basarat** [comment]
> Shouldn't it mention the package.json json member here ?

not sure what you mean?

**Comment by basarat** [comment]
Closing for now to keep queue clean. Feel free to discuss further :rose:
