### ISSUE TITLE
Typings for ntypescript?

### ISSUE THREAD

**Issue by SamuelMarks** [basarat/ntypescript#16]
Trying [typescript-book/docs/compiler/parser.md#sample-usage](https://github.com/basarat/typescript-book/blob/1dc5a4b1a587825333167a17a048e92715b2910e/docs/compiler/parser.md#sample-usage):

```
import * as ts from "ntypescript";

function printAllChildren(node: ts.Node, depth = 0) {
    console.log(new Array(depth + 1).join('----'),
                ts.syntaxKindToName(node.kind), node.pos, node.end);
    depth++;
    node.getChildren().forEach(c=> printAllChildren(c, depth));
}

var sourceCode = `
var foo = 123;
`.trim();

var sourceFile = ts.createSourceFile('foo.ts', sourceCode, ts.ScriptTarget.ES5, true);
printAllChildren(sourceFile);
```

Even after running `npm install ntypescript@latest --save --save-exact`, my IDE (Atom) complains with: `Cannot find module 'ntypescript'`.

Looking around for a `*.d.t.s` file, and couldn't find it :. How shall I proceed?

Thanks for all suggestions

**Comment by SamuelMarks** [comment]
That's strange, for some reason `find -name '*.d.ts'` couldn't find it. This works:

```
/// <reference path='./node_modules/ntypescript/bin/typescript.d.ts' />
```

**Comment by basarat** [comment]
:rose:
