### ISSUE TITLE
tsx file compilation fail on optional properties

### ISSUE THREAD

**Issue by j6lim** [basarat/ntypescript#17]
`tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "amd",
    "jsx": "react"
  },
  "compileOnSave": false,
  "files": [
    "./main.tsx",
    "./typings/tsd.d.ts"
  ]
}
```

`tsd`:

```
tsd install react-global react-bootstrap --save 
```

`main.tsx`:

```
import * as React from 'react';
import { render } from 'react-dom';
import { Button } from 'react-bootstrap';

class App extends React.Component<{}, {}> {
  render() {
    return <Button bsSize="large" bsStyle="danger" > {"Button Text"} </Button>;
  }
}

render(<App />, document.getElementsByTagName("entrypoint")[0] );
```

`ntsc 1.201512090606.1` fails with these error messages

```
main.tsx(8,12): error TS2324: Property 'key' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonProps, any>> & ButtonProps'.
main.tsx(8,12): error TS2324: Property 'ref' is missing in type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonProps, any>> & ButtonProps'.
```

The error message says that 'key' and 'props' property must be given, but they are defined as optional on IntrinsicAttributes and IntrinsicClassicAttributes like this. 

in `react.d.ts`, line 2119~2125

```
    interface IntrinsicAttributes {
        key?: string | number;
    }

    interface IntrinsicClassAttributes<T> {
        ref?: string | ((classInstance: T) => void);
    }
```

`tsc` compiles `main.tsx` without problem.

This bug makes atom-typescript plugin glitchy while writing react apps with typescript.

**Comment by j6lim** [comment]
Rollbacked my atom-typescript plugin from 7.14.1 back to 7.9.0 and the above error disappeared. It seems that the trunk version of Typescript between those may be broken..

**Comment by basarat** [comment]
Please report here : https://github.com/microsoft/typescript/issues :rose: Would love to be linked into the issue :+1:
