### ISSUE TITLE
tsconfig.json exclude disregarded

### ISSUE THREAD

**Issue by idefy** [basarat/ntypescript#18]
It seems to totatly ignore the exclude configuration in the tsconfig.json and compiles as well the ignore files.
For instance I have the following configuration:
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules"
  ]
}

And it still compiles everything in the node_modules folder.
I am running it via node : npm run ntsc -w

**Comment by basarat** [comment]
@idefy I do nothing special here. If it doesn't work here it doesn't work in TypeScript official. If that is indeed the case, you can report that here : https://github.com/Microsoft/TypeScript/issues :rose:
