### ISSUE TITLE
No minify output option?

### ISSUE THREAD

**Issue by wklingler** [basarat/ntypescript#22]
I'm not seeing any option that would make the compiled js code be minified.  Is there an option for that that I'm just missing?

**Comment by basarat** [comment]
> Is there an option for that that I'm just missing?

There is no option. This is just an automation on TypeScript and the options do not differ from that :rose: 

TypeScript doesn't yet try to replace your complete toolchain ... just the ESNext -> ESNow part. You need webpack / uglify / whatever have you for the remaining portions :rose:
