### ISSUE TITLE
Support tsserver

### ISSUE THREAD

**Issue by SamuelMarks** [basarat/ntypescript#24]
AFAIK there are 3 files that need to be included: [tsserver.js](https://github.com/Microsoft/TypeScript/blob/master/lib/tsserver.js), [tsserverlibrary.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/tsserverlibrary.d.ts) and [tsserverlibrary.js](https://github.com/Microsoft/TypeScript/blob/master/lib/tsserverlibrary.js).

For example let's say I want to use a newer TypeScript compiler than the one bundled with Jetbrains:
![ntypescript error](https://cloud.githubusercontent.com/assets/807580/19623877/54edc006-992a-11e6-9cf4-12c1f6b2a475.png)

I understand that this is listed in your "Design incompatibilities" section of your README.md.

What is your reasoning for excluding it? - File size? - Any chance of convincing you to include it?

**Comment by basarat** [comment]
> What is your reasoning for excluding it

The goal was opening up the API. tsserver API opening doesn't give any advantage over just using `typescript`. 

PS : I've moved to https://github.com/basarat/byots as it just uses `typescript` + still opens up the API. 

Please let me know if I am wrong or you still want to do something here :rose:
