### ISSUE TITLE
typescriptServices.d.ts(5082,44): error TS1110: Type expected.

### ISSUE THREAD

**Issue by s-panferov** [basarat/ntypescript#6]
It looks like that an error is in the file:

```
    function isTemplateLiteralKind(kind: SyntaxKind): boolean;
    function isBindingPattern(node: Node): ;
    function isInAmbientContext(node: Node): boolean;
```

**Comment by helarqjsc** [comment]
It's because the output type for `function isBindingPattern(node: Node): ;` isn't specified. 
I'm guessing it returns boolean, so it should be: ` function isBindingPattern(node: Node): boolean;`

**Comment by nycdotnet** [comment]
This is interesting because our `bin/typescriptServices.d.ts` file is about 5x longer than the one in TypeScript.  I'm looking into it.

**Comment by basarat** [comment]
Because of this bug : https://github.com/Microsoft/TypeScript/issues/3761

And a fix is on the way : https://github.com/Microsoft/TypeScript/pull/3763

I've been fixing it manually (in the verification step https://github.com/TypeStrong/ntypescript/blob/master/CONTRIBUTING.md#manually). I'll do that again right now for a new publish

**Comment by basarat** [comment]
> This is interesting because our bin/typescriptServices.d.ts file is about 5x longer than the one in TypeScript.

Because we make the `internal` API's public ;) I move the responsibility from the TS team to the API consumer :rose: 

Code : https://github.com/TypeStrong/ntypescript/blob/master/prepare.sh#L16-L18

**Comment by basarat** [comment]
Published with manual fix. Leaving open till its fixed upstream

**Comment by s-panferov** [comment]
@basarat thanks!

**Comment by nycdotnet** [comment]
Thanks, Bas.

**Comment by basarat** [comment]
Fixed upstream 🌹
