### ISSUE TITLE
What is the update frequency of the package?

### ISSUE THREAD

**Issue by s-panferov** [basarat/ntypescript#8]
@basarat Hello, thanks for the great package!

I have one question. The latest build was 6 days ago. I thought the idea was to publish 'nightly' builds periodically using Travis or something like that. Something is broken?

**Comment by basarat** [comment]
> I thought the idea was to publish 'nightly' builds periodically using Travis or something like that. Something is broken

This didn't happen for whatever reason : https://github.com/TypeStrong/ntypescript/blob/master/CONTRIBUTING.md#travis

**Comment by basarat** [comment]
Currently I just update some file using github UI e.g. : https://github.com/TypeStrong/ntypescript/commit/00d25ec1958011d87f9b3fd31be1296c9de89d3a to kick off a build

This isn't going to be the _permanent_ way which is why its been left undocumented ATM :rose:

**Comment by basarat** [comment]
I've researched more and just _flicked a switch_ at https://nightli.es/ 

Let's see how it goes in a few days :rose:

**Comment by s-panferov** [comment]
@basarat thanks again for what you are doing! Could you please publish the latest version on npm?

**Comment by basarat** [comment]
> Could you please publish the latest version on npm?

should have happened automatically, but something's changed on NPM : https://travis-ci.org/TypeStrong/ntypescript#L230 

I've published manually for now.

**Comment by s-panferov** [comment]
@basarat thanks!
