### ISSUE TITLE
compiler don't insert tsx compilation result to project common build out file.

### ISSUE THREAD

**Issue by stepancar** [basarat/ntypescript#9]
@basarat Hello, thanks for the great package! It's very convinient tool!  

I have issue which  don't face before. I start new ts project on another PC. (install npm, ntypescript, tsd)
added tsx, ts files to project. setted out compiler option. In result of compilation I see that compiled file contains only definitions from *.ts files. but tsx compiled to the same directory as tsx file.
atteched screen https://www.dropbox.com/s/90c3r4a1vjikz4j/ntypescriptIssue.png?dl=0.
Maybe a'm not correct? 
Thank you!

**Comment by basarat** [comment]
Don't use "out" with external modules. (It should be a compiler error but unfortunately isn't) 🌹

**Comment by stepancar** [comment]
@basarat, thank you for your answer and for your realy good work!
